export const siteIdentity = {
  name: 'Aqib Ops',
  alias: '',
  fullName: 'Aqib Ops',
  seoName: 'Aqib Ops',
  defaultUrl: 'https://aqibops.xyz',
  logoPath: '/aqib.png',
  email: 'AqibOpscontact@gmail.com',
  xProfile: 'https://x.com/AqibOps',
  linkedinProfile: 'https://www.linkedin.com/in/aqibops',
  whatsappProfile: 'https://wa.me/923432142032',
  twitterHandle: '@AqibOps',
  locale: 'en_US',
  language: 'en',
  keywords: [
    'n8n',
    'n8n automation',
    'n8n automation expert',
    'n8n workflow',
    'n8n workflows',
    'n8n workflow automation',
    'n8n expert',
    'n8n developer',
    'n8n automation expert freelance',
    'hire n8n developer',
    'n8n integration',
    'n8n integrations',
    'n8n api integration',
    'n8n chatbot',
    'n8n chatbot automation',
    'n8n ai automation',
    'n8n ai agents',
    'n8n automation workflow',
    'build n8n workflows',
    'n8n specialist',
    'n8n automation specialist',
    'n8n consultant',
    'n8n backend automation',
    'n8n webhooks',
    'n8n data automation',
    'n8n crm automation',
    'n8n marketing automation',
    'n8n email automation',
    'n8n whatsapp automation',
    'n8n bot development',
    'n8n automation services',
    'n8n workflow examples',
    'n8n ai automation case study',
    'n8n vs zapier automation expert',
    'automation engineer n8n',
    'ai automation consultant n8n',
    'workflow automation expert',
    'integration specialist n8n',
    'n8n automation tutorial',
    'advanced n8n workflows',
    'n8n business automation',
    'n8n real world projects',
    'build in public n8n',
    'ai automation workflows',
    'n8n automation templates',
    'n8n openai workflows',
    'automation',
    'workflow automation',
    'business automation',
    'process automation',
    'ai automation',
    'automation expert',
    'automation consultant',
    'automation system',
    'automation workflow',
    'automation setup',
    'custom automation',
    'automation services',
    'automation integration',
    'task automation',
    'digital automation',
    'smart automation',
    'intelligent automation',
    'ai',
    'ai agent',
    'ai agents',
    'ai automation agent',
    'ai chatbot',
    'ai chatbots',
    'chatbot development',
    'chatbot automation',
    'conversational ai',
    'gpt chatbot',
    'chatgpt',
    'chatgpt automation',
    'openai',
    'openai integration',
    'gpt-4',
    'gpt automation',
    'ai workflow',
    'ai tools integration',
    'ai system',
    'ai assistant',
    'ai business automation',
    'ai solution',
    'zapier',
    'zapier automation',
    'zapier expert',
    'zapier integration',
    'zapier workflow',
    'make',
    'make.com',
    'integromat',
    'make automation',
    'make.com expert',
    'make integration',
    'no code automation',
    'low code automation',
    'nocode tools',
    'lowcode tools',
    'api',
    'api integration',
    'rest api',
    'webhook',
    'webhooks',
    'third party integration',
    'system integration',
    'software integration',
    'backend integration',
    'database integration',
    'cloud integration',
    'google sheets automation',
    'airtable automation',
    'excel automation',
    'data automation',
    'data processing',
    'data syncing',
    'data pipeline',
    'data scraping',
    'web scraping',
    'data extraction',
    'automation scripts',
    'email automation',
    'email marketing automation',
    'lead generation automation',
    'lead scraping',
    'marketing automation',
    'sales automation',
    'crm automation',
    'customer automation',
    'funnel automation',
    'sales funnel',
    'outreach automation',
    'cold email automation',
    'social media automation',
    'instagram automation',
    'facebook automation',
    'twitter automation',
    'linkedin automation',
    'youtube automation',
    'content automation',
    'posting automation',
    'scheduling automation',
    'whatsapp automation',
    'whatsapp bot',
    'telegram bot',
    'telegram automation',
    'discord bot',
    'messenger bot',
    'sms automation',
    'notification automation',
    'ecommerce automation',
    'shopify automation',
    'woocommerce automation',
    'amazon automation',
    'order automation',
    'inventory automation',
    'dropshipping automation',
    'saas automation',
    'startup automation',
    'business workflow automation',
    'enterprise automation',
    'automation strategy',
    'automation consulting',
    'automation optimization',
    'workflow optimization',
    'system optimization',
    'python automation',
    'javascript automation',
    'nodejs automation',
    'backend development',
    'scripting automation',
    'custom scripts',
    'automation coding',
    'dev automation',
    'server automation',
    'integration expert',
    'workflow expert',
    'automation expert',
    'ai automation expert',
    'zapier expert',
    'make expert',
    'n8n expert',
    'chatbot expert',
    'api expert',
    'ai developer',
    'automation developer',
    'business process automation',
    'digital transformation',
    'productivity automation',
    'operations automation',
    'workflow builder',
    'automation engineer',
    'ai integration expert',
    'system builder',
    'tech automation',
    'scalable automation',
    'high level automation systems',
  ],
} as const;
