export const siteIdentity = {
  name: 'Aqib Mehmood',
  alias: '',
  fullName: 'Aqib Mehmood',
  seoName: 'Aqib Mehmood',
  defaultUrl: 'https://aqib.eu.cc',
  logoPath: 'https://res.cloudinary.com/dw0pjpqsu/image/upload/v1775662677/aqib_etvmzr.png',
  email: '',
  xProfile: '',
  linkedinProfile: '',
  whatsappProfile: 'https://wa.me/923432142032',
  twitterHandle: '',
  locale: 'en_US',
  language: 'en',
  keywords: [
    'aqib mehmood video editor',
    'video editing portfolio',
    'youtube video editor',
    'video editor for creators',
    'short form video editing',
    'youtube shorts editor',
    'reels editor',
    'high retention video editing',
    'video editing for personal brands',
    'content repurposing editor',
    'creator video editing service',
    'video editor for business content',
    'talking head video editor',
    'podcast clip editor',
    'subtitle video editor',
    'retention focused video editing',
  ],
} as const;
